In [1]:
import torch
print(torch.__version__)

2.4.0+cu121


# Tensors
## Create tensors


In [2]:
##scaler
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
#get tensor back as python int
scaler.item()

7

In [5]:
##Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim##no of brackets

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
##Matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
##TENSOR
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

# Random tensors
Neural network starts with random numbers and adjust those number to better representations.

In [14]:
##Random tensors
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2977, 0.5698, 0.5472, 0.2742],
        [0.1217, 0.7029, 0.3276, 0.9873],
        [0.5062, 0.8259, 0.4925, 0.1169]])

In [15]:
random_tensor.ndim

2

In [16]:
#create random tensor with similar shapes to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))#height,width,color channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [17]:
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

# Range tensors

In [20]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ten_zeros=torch.arange(start=0,end=1000,step=20)
ten_zeros

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240, 260,
        280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540,
        560, 580, 600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820,
        840, 860, 880, 900, 920, 940, 960, 980])

In [22]:
## same size tensors
ten_zeros=torch.zeros_like(input=ten_zeros)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [23]:
float_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_tensor

tensor([3., 6., 9.])

In [24]:
float_tensor.dtype

torch.float32

# Tensor Datatypes

In [25]:
## 3 imp parameter dtype,require_grad,device
float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16,device=None,requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float32,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


In [29]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

# Getting information from tensor

In [31]:
data=torch.rand(size=(3,3),dtype=torch.float16)

In [32]:
print(f"Data Type of Tensor: {data.dtype}")
print(f"Shape of tensor: {data.shape}")
print(f"Device tensor is on: {data.device}")

Data Type of Tensor: torch.float16
Shape of tensor: torch.Size([3, 3])
Device tensor is on: cpu


# Manipulation Tensors
## Addition
## Multiplication
## Division
## Matrix Multiplication

In [33]:
#create tensor
tensor=torch.tensor([1,2,3],dtype=torch.float32)
print(tensor)

tensor([1., 2., 3.])


In [34]:
##Tensor addition
tensor+10

tensor([11., 12., 13.])

In [35]:
#Tensor multiplication
tensor*10

tensor([10., 20., 30.])

In [36]:
#tensor SUbtraction
tensor-10

tensor([-9., -8., -7.])

In [37]:
##using pytorch method
torch.mul(tensor,20)

tensor([20., 40., 60.])

In [38]:
torch.add(tensor,10)

tensor([11., 12., 13.])

# Matrix Multiplication
## Element wise
## Dot Product

In [39]:
#matrix multiplication
#Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1., 2., 3.]) * tensor([1., 2., 3.])
Equals: tensor([1., 4., 9.])


In [40]:
#dot product
torch.matmul(tensor,tensor)

tensor(14.)

In [41]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14.)
CPU times: user 2.43 ms, sys: 0 ns, total: 2.43 ms
Wall time: 5.16 ms


In [42]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 40 µs, sys: 8 µs, total: 48 µs
Wall time: 50.3 µs


tensor(14.)

In [43]:
##Dot product with proper shape of tensors

In [44]:
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])
tensor_C=torch.matmul(tensor_A,tensor_B)
print(tensor_C)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [46]:
tensor_C=torch.matmul(tensor_A,tensor_B.T)
print(tensor_C)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


# Find min,max,sum etc

In [47]:
##create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
torch.min(x)

tensor(0)

In [49]:
torch.max(x)

tensor(90)

In [50]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))## torch.mean() requires float32 datatype

In [ ]:
## find sum
torch.sum(x)

In [51]:
## finding the position of min and max
x.argmin()

tensor(0)

In [52]:
x.argmax()

tensor(9)

# Reshaping,view,stacking,squeezing and unsqueezing,permute

In [53]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
#Reshape
x.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
z=x.view(1,9)## change in z changes in x as both of them share same memory
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
## Stack tensors
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [58]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
x_reshaped.squeeze().shape

torch.Size([9])

In [61]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

##remove extra dimensions
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [62]:
##Unqueezed
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

##add extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [63]:
##torch permute
x_original=torch.rand(size=(224,224,3))
print(x_original.shape)
x_permuted=x_original.permute(2,0,1)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


# Indexing

In [64]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
x[0][0]

tensor([1, 2, 3])

In [67]:
x[0][0][0]

tensor(1)

In [68]:
x[0][2][2]

tensor(9)

In [69]:
x[:,1,1]

tensor([5])

In [70]:
x[0,0,0]

tensor(1)

In [71]:
x[0,:,2]

tensor([3, 6, 9])

# Tensors and Numpy

In [72]:
import numpy as np
import torch
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)## from numpy to pytorch tensor will have numpy datatype i.e float 64 unless specifiedotherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
## change the array
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
# change the tensor what happens to 'numpy_tensor'
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility

In [76]:
torch.rand(3,3)

tensor([[0.2073, 0.8386, 0.2625],
        [0.8878, 0.7395, 0.9829],
        [0.3256, 0.4114, 0.2962]])

In [77]:
import torch
import random
##set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_A=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Run on GPU

In [80]:
import torch
torch.cuda.is_available()

True

In [84]:
##setting device
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [85]:
#count tye number of device
torch.cuda.device_count()

1

In [86]:
## Putting tensors and models on gpu
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)


tensor([1, 2, 3]) cpu


In [87]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [88]:
## moving tensors to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [89]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])